# Generated by Django 4.1.2 on 2022-10-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_place_restaurant_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='rest1', max_length=100),
        ),
    ]
