# Generated by Django 4.1.2 on 2022-10-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='place',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
